language: go
go: 1.11.x

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/v0.3.0/operator-sdk-v0.3.0-x86_64-linux-gnu -o $GOPATH/bin/operator-sdk
  - chmod +x $GOPATH/bin/operator-sdk

install: true # don't `go get` a bunch of junk, we'll get it with dep

script:
  - export OPERATOR_VERSION=$(git describe --always --dirty --tags)
  - dep ensure -vendor-only
  - operator-sdk build travisci/worker-operator:$OPERATOR_VERSION

deploy:
  provider: script
  script: hack/docker-push
  on:
    repo: travis-ci/worker-operator
    all_branches: true

notifications:
  email: false
